name: nature_explorer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  geolocator: ^7.6.2
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.4+4
  google_generative_ai: ^0.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  build_runner: ^2.1.7

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env